### ISSUE TITLE
Add a copy to clipboard icon and function

### ISSUE THREAD

**Issue by shadowbq** [banagale/FileKitty#1]
# New Feature Request: 

Using QT, create a simple icon + button function that selects all the text, and copies to the proper clipboards.

**Comment by shadowbq** [comment]
Simple reference: https://realpython.com/python-menus-toolbars/

**Comment by banagale** [comment]
Completed in #2.  Thanks for the request!  Please keep it up.

**Comment by banagale** [comment]
@shadowbq curious if you've used the latest build / have any new feature requests?
